### ISSUE TITLE
Post-AGMAPIData does not work

### ISSUE THREAD

**Issue by hicoo56** [Actifio/AGMPowerCLI#17]
Hello,

I'm trying to create Org using "Post-AGMAPIData" and i'm facing a "10023" error code, even documentation example failed such as :

Post-AGMAPIData -endpoint /org -body '{ "description": "Melbourne test team","name": "MelTeam1" }' -datefields "modifydate,createdate"

err_code 10023

I also tried to create an Org using "New-AGMOrg" with :
New-AGMOrg -jsonbody $json

Where $json is:

{ "type":"organizationRest", "name":"avtest", "description":"test org" }

"New-AGMOrg" command works without -jsonbody option but unfortunately it does not seems possible to add "memberlist" without it.

Am I missing something ?

I use AGM version: 11.0.1.7943 and the latest version of this project.

Thank you for your support

**Comment by aussiestorblog** [comment]
The description "Post-AGMAPIData does not work " is not accurate given its used in a vast number of other functions.   For instance   "New-AGMOrg" works, because "Post-AGMAPIData" works.   

I have pulled the org examples you are following because  the Management Console is expecting more info in the JSON and rather than re-write them, given they also lead people to use the direct post functions, which need well formed JSON,  we would rather they used the end point commands supplied.

Having created an org with New-AGMOrg you can add or remove applications, hosts and logical groups using these functions:

    'Set-AGMOrgApplication',
    'Set-AGMOrgHost',
    'Set-AGMOrgLogicalGroup',

I would expect users to build an Org using the Management Console and then add/remove hosts and apps using API as those things get created.

**Comment by aussiestorblog** [comment]
I added a user story for org creation and a sample edit:

https://github.com/Actifio/AGMPowerCLI#user-story-org-creation
