### ISSUE TITLE
New-AGMHost using appliance id in place of cluster id

### ISSUE THREAD

**Issue by tejajrk** [Actifio/AGMPowerCLI#25]
New-AGMHost -applianceid 4207 -clusterid 144342333183 -hostname "secured-sql-server-2017" -friendlyname "sqlserverxpress1" -secret xxxxxxx -ipaddress "10.0.0.7"

@type        : hostRest
friendlypath : sqlserverxpress1
hostname     : secured-sql-server-2017-express-win-s-1-vm
ipaddress    : 10.0.0.7
sources      : {@{clusterid=4207; cert_revoked=False}}
hosttype     : generic
orglist      : {@{id=}}
udsagent     : 
cert_revoked : False

Above is the response. And host is not added. But when I change the command to below it works well.
New-AGMHost -applianceid 144342333183 -clusterid 144342333183 -hostname "secured-sql-server-2017" -friendlyname "sqlserverxpress1" -secret xxxxxxx -ipaddress "10.0.0.7"

I see the code is trying to change clusterid to applianceid if passed. But both are different and it's little bit confusing.

**Comment by aussiestorblog** [comment]
Two things.

1) You don't need to use both clusterid and applianceid, just specify one of them.   They are actually the same thing.   This is a source of confusion, but there is nothing I can do about it as the API uses the term clusterID while the GUI uses the term applianceid.   If have added a check so that if you specify both, we will reject the command.

2). If you specify a non-existent clusterid, the platform replies with the rather confusing message you are seeing.  Ideally platform would reply and say 'that clusterid' does not exist, but then platform expects us to use a real clusterid.   So what I have done is add a check to ensure the clusterid being specified does exist.

Both changes are in release 0.0.0.50 so please upgrade
